/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;



import Connect.NhaCungCapVPP_Connect;

import Model.NhaCungCap_VPP;


import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class QuanLyNCCVPP extends javax.swing.JFrame {
    private DefaultTableModel dtmNCC ;
    private ArrayList<NhaCungCap_VPP> dsNCC = null;
    private ArrayList<NhaCungCap_VPP> dssTenNCC = null;
    /**
     * Creates new form QuanLyNXB
     */
    public QuanLyNCCVPP( String title) {
        initComponents();
        this.setTitle(title);
        hienThiToanBoThongTin();
    }
private void hienThiToanBoThongTin() {
        NhaCungCapVPP_Connect nccConn = new NhaCungCapVPP_Connect();
        dsNCC = nccConn.layToanBoNhaCungCap_VPP();
        dtmNCC = new DefaultTableModel();
        dtmNCC.addColumn("Mã nhà cung cấp");
        dtmNCC.addColumn("Tên nhà cung cấp");
        dtmNCC.addColumn("Số điện thoại");
        dtmNCC.addColumn("Địa chỉ");
        dtmNCC.addColumn("Email");
  
        dtmNCC.setRowCount(0);
        for (NhaCungCap_VPP s : dsNCC){
            Vector<Object> vec = new Vector<Object>();
            vec.add(s.getMaNCCVPP());
            vec.add(s.getTenNCCVPP());
            vec.add(s.getSDT());
            vec.add(s.getDiaChi());
            vec.add(s.getEmail());
          
            dtmNCC.addRow(vec);	
        }
        NCCTable.setModel(dtmNCC);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        NCCTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MaNVLabel = new javax.swing.JLabel();
        MaNCCInput = new javax.swing.JTextField();
        TenNVLabel = new javax.swing.JLabel();
        TenNCCInput = new javax.swing.JTextField();
        SDTLabel = new javax.swing.JLabel();
        SDTInput = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        CCCDLabel = new javax.swing.JLabel();
        DCInput = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        TimNhanVienLabel = new javax.swing.JLabel();
        ThongTinNhanVienLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TKNCCBtn = new javax.swing.JButton();
        TimKiemInput = new javax.swing.JTextField();
        NhanTenLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NCCTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NCCTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(NCCTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MaNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaNVLabel.setText("Mã nhà cung cấp");

        TenNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TenNVLabel.setText("Tên nhà cung cấp");

        SDTLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SDTLabel.setText("Số điện thoại");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(SDTLabel)
                            .addGap(34, 34, 34))
                        .addComponent(TenNVLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(MaNVLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MaNCCInput, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(TenNCCInput)
                    .addComponent(SDTInput))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaNCCInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenNVLabel)
                    .addComponent(TenNCCInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDTInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        CCCDLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CCCDLabel.setText("Địa chỉ");

        DCInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCInputActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCCDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailInput)
                    .addComponent(DCInput, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(DCInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CCCDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmailLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        AddBtn.setText("Thêm");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Cập nhật");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Nhập lại");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Xóa");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TimNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TimNhanVienLabel.setForeground(new java.awt.Color(255, 0, 0));
        TimNhanVienLabel.setText("Tìm nhà cung cấp văn phòng phẩm");

        ThongTinNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ThongTinNhanVienLabel.setForeground(new java.awt.Color(255, 0, 0));
        ThongTinNhanVienLabel.setText("Thông tin nhà cung cấp văn phòng phẩm");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TKNCCBtn.setText("Tìm kiếm");
        TKNCCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKNCCBtnActionPerformed(evt);
            }
        });

        NhanTenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NhanTenLabel.setText("Nhập tên nhà cung cấp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimKiemInput)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(NhanTenLabel)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(TKNCCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(NhanTenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimKiemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(TKNCCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimNhanVienLabel)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ThongTinNhanVienLabel)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ThongTinNhanVienLabel)
                    .addComponent(TimNhanVienLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NCCTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NCCTableMouseClicked
        int select = NCCTable.getSelectedRow();
            
				if(select==-1) return ;
				
                                //lấy thông tin trong table
				NhaCungCap_VPP ncc = new NhaCungCap_VPP();
				ncc.setMaNCCVPP((String) NCCTable.getValueAt(select, 0));
                            
                                ncc.setTenNCCVPP((String) NCCTable.getValueAt(select, 1));
				ncc.setSDT((String) NCCTable.getValueAt(select, 2));
				ncc.setDiaChi((String) NCCTable.getValueAt(select, 3));
				ncc.setEmail((String) NCCTable.getValueAt(select, 4));
                           
				
				//đưa thông tin lên panelTop
				MaNCCInput.setText(ncc.getMaNCCVPP());                    
                                TenNCCInput.setText(ncc.getTenNCCVPP());
                                SDTInput.setText(ncc.getSDT());
                                DCInput.setText(ncc.getDiaChi());
                                EmailInput.setText(ncc.getEmail());
                          
    }//GEN-LAST:event_NCCTableMouseClicked

    private void TKNCCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKNCCBtnActionPerformed
    String ten = TimKiemInput.getText();
        
        NhaCungCapVPP_Connect nccConn = new NhaCungCapVPP_Connect();
        
        dssTenNCC = nccConn.laySachTheoTenNhaCungCap(ten);
        
        //show all data
        if (TimKiemInput.getText().length()==0)
            hienThiToanBoThongTin();
        //tìm kiếm theo tên sách
        else{
            dtmNCC.setRowCount(0);
            for (NhaCungCap_VPP s : dssTenNCC){
            Vector<Object> vec = new Vector<Object>();
            vec.add(s.getMaNCCVPP());
            vec.add(s.getTenNCCVPP());
            vec.add(s.getSDT());
            vec.add(s.getDiaChi());
            vec.add(s.getEmail());
          
            dtmNCC.addRow(vec);
            }
        }

    }//GEN-LAST:event_TKNCCBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
            int select = NCCTable.getSelectedRow();
				if(select==-1)  return ;
				String maNCC = (String) NCCTable.getValueAt(select, 0);
				//JOptionPane.showMessageDialog(null,jTable_Books.getValueAt(select, 0) );
				int active = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa", "Xác Nhận Xóa", JOptionPane.OK_CANCEL_OPTION);
				if(active==JOptionPane.OK_OPTION)
				{
					xuLyXoa(maNCC);
					//JOptionPane.showMessageDialog(null,maSach );
				}
    }//GEN-LAST:event_DeleteBtnActionPerformed
protected void xuLyXoa(String maNCC) {
		 NhaCungCapVPP_Connect nccConn = new NhaCungCapVPP_Connect();
		int active= nccConn.Xoa(maNCC);
		if(active > 0)
		{
			JOptionPane.showMessageDialog(null, "Xóa thành công!");
			hienThiToanBoThongTin();
		}
		else
		{
			JOptionPane.showMessageDialog(null, "Xóa thất bại");	
		}
		
	}
    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
            MaNCCInput.setText("");
            TenNCCInput.setText("");
				
            DCInput.setText("");
            EmailInput.setText("");
            SDTInput.setText("");
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
            
				NhaCungCap_VPP ncc = new NhaCungCap_VPP();
				ncc.setMaNCCVPP(MaNCCInput.getText());
				ncc.setTenNCCVPP(TenNCCInput.getText());
                                ncc.setSDT(SDTInput.getText());
				
				ncc.setDiaChi(DCInput.getText());
				ncc.setEmail(EmailInput.getText());
				NhaCungCapVPP_Connect nccConn = new NhaCungCapVPP_Connect();
				int active = nccConn.update(ncc);
				if (active>0)
				{
					JOptionPane.showMessageDialog(null, "Chỉnh sửa thông tin thành công");
				}
				else 
				{
					JOptionPane.showMessageDialog(null, "Chỉnh sửa thất bại");
				}
                                hienThiToanBoThongTin();
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        if(MaNCCInput.getText().length()==0 ||  
						TenNCCInput.getText().length()==0 || DCInput.getText().length()==0 || EmailInput.getText().length()==0 ||
						SDTInput.getText().length()==0) return ;
				
				//NXB nxb = (NXB) NXBInput.getSelectedItem();
				NhaCungCap_VPP ncc = new NhaCungCap_VPP();
				ncc.setMaNCCVPP(MaNCCInput.getText());
				ncc.setTenNCCVPP(TenNCCInput.getText());
                                ncc.setSDT(SDTInput.getText());
				
				ncc.setDiaChi(DCInput.getText());
				ncc.setEmail(EmailInput.getText());
				
				int x =JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muôn thêm nhà cung cấp", "Xác nhận thêm",JOptionPane.OK_CANCEL_OPTION);
				if(x==JOptionPane.OK_OPTION)
				{
					xuLyThemMoi(ncc);	
				}
				else return;
    }//GEN-LAST:event_AddBtnActionPerformed
protected void xuLyThemMoi(NhaCungCap_VPP ncc) {
		
                NhaCungCapVPP_Connect nccConnAdd = new NhaCungCapVPP_Connect();
		int active = nccConnAdd.themMoi(ncc);
		if(active > 0 )
		{
			JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                                MaNCCInput.setText("");
                                TenNCCInput.setText("");
                                DCInput.setText("");
                                EmailInput.setText("");
                                SDTInput.setText("");
                                hienThiToanBoThongTin();
//                      
			
		}
		else
		{
			JOptionPane.showMessageDialog(null, "Thêm mới thất bại");
		}
		
	}
    private void DCInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNCCVPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNCCVPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNCCVPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNCCVPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }
    void showWindow() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNCCVPP("quản lý nhà cung cấp văn phòng phẩm").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JLabel CCCDLabel;
    private javax.swing.JTextField DCInput;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField MaNCCInput;
    private javax.swing.JLabel MaNVLabel;
    private javax.swing.JTable NCCTable;
    private javax.swing.JLabel NhanTenLabel;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JTextField SDTInput;
    private javax.swing.JLabel SDTLabel;
    private javax.swing.JButton TKNCCBtn;
    private javax.swing.JTextField TenNCCInput;
    private javax.swing.JLabel TenNVLabel;
    private javax.swing.JLabel ThongTinNhanVienLabel;
    private javax.swing.JTextField TimKiemInput;
    private javax.swing.JLabel TimNhanVienLabel;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
