/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Connect.HoaDon_Connect;
import Connect.Sach_Connect;
import Model.HoaDon;
import Model.Sach;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dat
 */
public class ThongKe extends javax.swing.JFrame {
private DefaultTableModel dtmSach =null, dtmHoaDon =null, dtmBanChay = null;
private ArrayList<HoaDon> dshd_thongke =null;
private ArrayList<Sach> dss ;
private double tongTien =0;
private DecimalFormat df = new DecimalFormat("###,###,###");
    /**
     * Creates new form ThongKe
     */
    public ThongKe(String title) {
        initComponents();
        this.setTitle(title);
        this.setLocationRelativeTo(null);
        hienThiHoaDon();
        hienThiSachTonKho();
        hienThiSachBanChay();
    }
    
    private void hienThiSachTonKho() {
        Sach_Connect sach_conn = new Sach_Connect();
        dss = sach_conn.laySachConDuoiTon((int)SLBaoDongInput.getValue());
        dtmSach = new DefaultTableModel();
        dtmSach.addColumn("Mã sách");
        dtmSach.addColumn("Tên sách");
        dtmSach.addColumn("Tên nhà xuất bản");
        dtmSach.addColumn("Số lượng tồn");
        dtmSach.setRowCount(0);
        for(Sach s : dss){
            Vector<Object> vec = new Vector<Object>();
            vec.add(s.getMaSach());
            vec.add(s.getTenSach());
            vec.add(s.getMaNXB());
            vec.add(s.getSoLuong());

            dtmSach.addRow(vec);
        }
        NeedBookTable.setModel(dtmSach);
    }
    
    private void hienThiHoaDon() {
        Calendar cal = Calendar.getInstance();
        MonthInput.setSelectedIndex(cal.get(Calendar.MONTH) + 1); // Tháng bắt đầu từ 0 nên cần +1 để lấy tháng thực tế
        YearInput.setText(Integer.toString(cal.get(Calendar.YEAR)) );
        
        dtmHoaDon = new DefaultTableModel();
        dtmHoaDon.addColumn("Mã hóa Đơn");
        dtmHoaDon.addColumn("Mã Nhân Viên");
        dtmHoaDon.addColumn("Ngày lập");
        dtmHoaDon.addColumn("Tổng tiền");
        dtmHoaDon.setRowCount(0);
        HoaDon_Connect hd_connect = new HoaDon_Connect();
        dshd_thongke = hd_connect.layToanBoHoaDonTheoThangNam(Integer.toString(MonthInput.getSelectedIndex()), YearInput.getText());
        tongTien = 0;
        for(HoaDon hd : dshd_thongke){
            tongTien = tongTien + hd.getTongTien();
            Vector<Object> vec = new Vector<Object>();
            vec.add(hd.getMaHD());
            vec.add(hd.getMaNV());
            vec.add(hd.getNgaylap());
            vec.add(df.format(hd.getTongTien()));
            dtmHoaDon.addRow(vec);
        }
        HDTable.setModel(dtmHoaDon);
        TotalOutput.setText(df.format(tongTien) + " vnđ");
    }
    
    private void hienThiSachBanChay() {
        Calendar cal = Calendar.getInstance();
        BanChayMonthInput.setSelectedIndex(cal.get(Calendar.MONTH) + 1); // Tháng bắt đầu từ 0 nên cần +1 để lấy tháng thực tế
        BanChayYearInput.setText(Integer.toString(cal.get(Calendar.YEAR)) );
        Sach_Connect sach_conn = new Sach_Connect();
        dss = sach_conn.laySachBanChay(TopBanChayInput.getValue().toString(), Integer.toString(BanChayMonthInput.getSelectedIndex()), BanChayYearInput.getText());
        dtmBanChay = new DefaultTableModel();
        dtmBanChay.addColumn("Mã sách");
        dtmBanChay.addColumn("Tên sách");
        dtmBanChay.addColumn("Số lượng đã bán");
        dtmBanChay.setRowCount(0);
        for(Sach s : dss){
            Vector<Object> vec = new Vector<Object>();
            vec.add(s.getMaSach());
            vec.add(s.getTenSach());
            vec.add(s.getSoLuong());

            dtmBanChay.addRow(vec);
        }
        BanChayTable.setModel(dtmBanChay);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TKLable = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        HDPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        HDTable = new javax.swing.JTable(dtmHoaDon);
        MonthInput = new javax.swing.JComboBox<>();
        YearInput = new javax.swing.JTextField();
        TKBtn = new javax.swing.JButton();
        MonthLabel = new javax.swing.JLabel();
        YearLabel = new javax.swing.JLabel();
        PrintHDBtn = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        TotalOutput = new javax.swing.JLabel();
        NeedBookPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NeedBookTable = new javax.swing.JTable(dtmSach);
        SLBaoDongLabel = new javax.swing.JLabel();
        SLBaoDongInput = new javax.swing.JSpinner(new SpinnerNumberModel(10, 10, 100, 10));
        TKNeedBookBtn = new javax.swing.JButton();
        PrintNeedBookBtn = new javax.swing.JButton();
        BanChayPane = new javax.swing.JPanel();
        BanChayMonthInput = new javax.swing.JComboBox<>();
        BanChayYearInput = new javax.swing.JTextField();
        BanChayYearLabel = new javax.swing.JLabel();
        BanChayMonthLabel = new javax.swing.JLabel();
        BanChayBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BanChayTable = new javax.swing.JTable();
        PrintBanChayBtn = new javax.swing.JButton();
        TopBanChayInput = new javax.swing.JSpinner(new SpinnerNumberModel(10, 0, 100, 1));
        BanChayTopLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TKLable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TKLable.setForeground(new java.awt.Color(0, 0, 255));
        TKLable.setText("THỐNG KÊ");

        jScrollPane2.setViewportView(HDTable);

        MonthInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        TKBtn.setBackground(new java.awt.Color(51, 153, 255));
        TKBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TKBtn.setForeground(new java.awt.Color(255, 255, 255));
        TKBtn.setText("Thống kê");
        TKBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TKBtnMouseClicked(evt);
            }
        });

        MonthLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MonthLabel.setText("Tháng");

        YearLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        YearLabel.setText("Năm");

        PrintHDBtn.setText("In bảng thông kê");
        PrintHDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintHDBtnActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalLabel.setText("Tổng tiền bán được của tháng :");

        TotalOutput.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TotalOutput.setText("0 vnđ");

        javax.swing.GroupLayout HDPaneLayout = new javax.swing.GroupLayout(HDPane);
        HDPane.setLayout(HDPaneLayout);
        HDPaneLayout.setHorizontalGroup(
            HDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HDPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MonthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(YearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(TKBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HDPaneLayout.createSequentialGroup()
                .addGroup(HDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HDPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrintHDBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HDPaneLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(TotalLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TotalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        HDPaneLayout.setVerticalGroup(
            HDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HDPaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(HDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKBtn)
                    .addComponent(YearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearLabel)
                    .addComponent(MonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthLabel))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel)
                    .addComponent(TotalOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrintHDBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Hóa đơn", HDPane);

        jScrollPane3.setViewportView(NeedBookTable);

        SLBaoDongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SLBaoDongLabel.setText("Số lượng của sách dưới :");

        TKNeedBookBtn.setBackground(new java.awt.Color(51, 153, 255));
        TKNeedBookBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TKNeedBookBtn.setForeground(new java.awt.Color(255, 255, 255));
        TKNeedBookBtn.setText("Thống kê");
        TKNeedBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TKNeedBookBtnMouseClicked(evt);
            }
        });

        PrintNeedBookBtn.setText("In bảng thống kê");
        PrintNeedBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintNeedBookBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NeedBookPaneLayout = new javax.swing.GroupLayout(NeedBookPane);
        NeedBookPane.setLayout(NeedBookPaneLayout);
        NeedBookPaneLayout.setHorizontalGroup(
            NeedBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NeedBookPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SLBaoDongLabel)
                .addGap(18, 18, 18)
                .addComponent(SLBaoDongInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(TKNeedBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NeedBookPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(NeedBookPaneLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(PrintNeedBookBtn)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        NeedBookPaneLayout.setVerticalGroup(
            NeedBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NeedBookPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(NeedBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NeedBookPaneLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(SLBaoDongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NeedBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TKNeedBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SLBaoDongInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(PrintNeedBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sách cần nhập", NeedBookPane);

        BanChayMonthInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BanChayYearLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BanChayYearLabel.setText("Năm");

        BanChayMonthLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BanChayMonthLabel.setText("Tháng");

        BanChayBtn.setBackground(new java.awt.Color(51, 153, 255));
        BanChayBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BanChayBtn.setForeground(new java.awt.Color(255, 255, 255));
        BanChayBtn.setText("Thống kê");
        BanChayBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BanChayBtnMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(BanChayTable);

        PrintBanChayBtn.setText("In bảng thống kê");
        PrintBanChayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBanChayBtnActionPerformed(evt);
            }
        });

        BanChayTopLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BanChayTopLabel.setText("TOP");

        javax.swing.GroupLayout BanChayPaneLayout = new javax.swing.GroupLayout(BanChayPane);
        BanChayPane.setLayout(BanChayPaneLayout);
        BanChayPaneLayout.setHorizontalGroup(
            BanChayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BanChayPaneLayout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(BanChayTopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TopBanChayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BanChayMonthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BanChayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(BanChayYearLabel)
                .addGap(18, 18, 18)
                .addComponent(BanChayYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BanChayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(BanChayPaneLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(PrintBanChayBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        BanChayPaneLayout.setVerticalGroup(
            BanChayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BanChayPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BanChayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BanChayMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BanChayYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BanChayYearLabel)
                    .addComponent(BanChayMonthLabel)
                    .addComponent(BanChayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BanChayTopLabel)
                    .addComponent(TopBanChayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrintBanChayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Bán chạy", BanChayPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TKLable)
                .addGap(348, 348, 348))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TKLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TKBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TKBtnMouseClicked
        HoaDon_Connect hd_connect = new HoaDon_Connect();
        String thang  = MonthInput.getSelectedItem().toString();
        String nam = YearInput.getText();
        dshd_thongke = hd_connect.layToanBoHoaDonTheoThangNam(thang, nam);
        tongTien = 0;
        dtmHoaDon.setRowCount(0);
        for(HoaDon hd : dshd_thongke){
            tongTien = tongTien + hd.getTongTien();
            Vector<Object> vec = new Vector<Object>();
            vec.add(hd.getMaHD());
            vec.add(hd.getMaNV());
            vec.add(hd.getNgaylap());
            vec.add(df.format(hd.getTongTien()));
            dtmHoaDon.addRow(vec);
        }
        HDTable.setModel(dtmHoaDon);
        TotalOutput.setText(df.format(tongTien) + " vnđ");
    }//GEN-LAST:event_TKBtnMouseClicked

    private void PrintHDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintHDBtnActionPerformed
        try {
            MessageFormat header = new MessageFormat("Danh sách hóa đơn tháng")  ;
            MessageFormat footer = new MessageFormat("Page{1,number,interger} ")  ;
            HDTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e2) {
                e2.printStackTrace();
        }
    }//GEN-LAST:event_PrintHDBtnActionPerformed

    private void TKNeedBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TKNeedBookBtnMouseClicked
        Sach_Connect sach_conn = new Sach_Connect();
        dss = sach_conn.laySachConDuoiTon((int)SLBaoDongInput.getValue());
        dtmSach.setRowCount(0);
        for(Sach s : dss){
            Vector<Object> vec = new Vector<Object>();
            vec.add(s.getMaSach());
            vec.add(s.getTenSach());
            vec.add(s.getMaNXB());
            vec.add(s.getSoLuong());

            dtmSach.addRow(vec);
        }
        NeedBookTable.setModel(dtmSach);
    }//GEN-LAST:event_TKNeedBookBtnMouseClicked

    private void PrintNeedBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintNeedBookBtnActionPerformed
        try {
            MessageFormat header = new MessageFormat("Danh sách loại sách cần nhập");
            MessageFormat footer = new MessageFormat("Page{1,number,interger}");
            NeedBookTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e2) {
                e2.printStackTrace();
        }
    }//GEN-LAST:event_PrintNeedBookBtnActionPerformed

    private void BanChayBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanChayBtnMouseClicked
         Sach_Connect sach_conn = new Sach_Connect();
        dss = sach_conn.laySachBanChay(TopBanChayInput.getValue().toString(), Integer.toString(BanChayMonthInput.getSelectedIndex()), BanChayYearInput.getText());
        dtmBanChay.setRowCount(0);
        for(Sach s : dss){
            Vector<Object> vec = new Vector<Object>();
            vec.add(s.getMaSach());
            vec.add(s.getTenSach());
            vec.add(s.getSoLuong());

            dtmBanChay.addRow(vec);
        }
        BanChayTable.setModel(dtmBanChay);
    }//GEN-LAST:event_BanChayBtnMouseClicked

    private void PrintBanChayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBanChayBtnActionPerformed
        try {
            MessageFormat header = new MessageFormat("Danh sách loại sách bán chạy");
            MessageFormat footer = new MessageFormat("Page{1,number,interger}");
            BanChayTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e2) {
                e2.printStackTrace();
        }
    }//GEN-LAST:event_PrintBanChayBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe("Thống kê").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanChayBtn;
    private javax.swing.JComboBox<String> BanChayMonthInput;
    private javax.swing.JLabel BanChayMonthLabel;
    private javax.swing.JPanel BanChayPane;
    private javax.swing.JTable BanChayTable;
    private javax.swing.JLabel BanChayTopLabel;
    private javax.swing.JTextField BanChayYearInput;
    private javax.swing.JLabel BanChayYearLabel;
    private javax.swing.JPanel HDPane;
    private javax.swing.JTable HDTable;
    private javax.swing.JComboBox<String> MonthInput;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JPanel NeedBookPane;
    private javax.swing.JTable NeedBookTable;
    private javax.swing.JButton PrintBanChayBtn;
    private javax.swing.JButton PrintHDBtn;
    private javax.swing.JButton PrintNeedBookBtn;
    private javax.swing.JSpinner SLBaoDongInput;
    private javax.swing.JLabel SLBaoDongLabel;
    private javax.swing.JButton TKBtn;
    private javax.swing.JLabel TKLable;
    private javax.swing.JButton TKNeedBookBtn;
    private javax.swing.JSpinner TopBanChayInput;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalOutput;
    private javax.swing.JTextField YearInput;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
